- hosts: localhost
  tasks:
    - name: Gettings Public IP from instance
      ec2_instance_facts:
        region: us-east-2
        filters:
          instance-state-name: running
      register: ec2_metadata
    - name: Add Public IP to variables
      set_fact:
        ip_from_ec2: "{{ ec2_metadata.instances[0].network_interfaces[0].association.public_ip }}"
    - debug:
        var: ip_from_ec2
    - name: Add host to group `webservers`
      add_host:
        host: "{{ ip_from_ec2 }}"
        groups: webservers

- hosts: webservers
  tasks:
    - name: Ping webservers
      action: ping
